### ISSUE TITLE
adult_5_2 with value 7 (Violence, suicide, homicide, abuse) returns "Undetermined"

### ISSUE THREAD

**Issue by KlausBlass** [ihmeuw/SmartVA-Analyze#21]
In the SmartVA-Analyze (Smart VA 2.2.0) app:
For the variable adult_5_2 (kind of injury or accident) a value of 7 (Violence, suicide, homicide, abuse) always returns “Undetermined” as the cause of death. All other values (1,2,3,4,5,6,11) return the expected cause.
(In Burkina Faso we currently have a lot of people killed by terrorists, whose cause of death is therefore not detected by SmartVA).
My analysis:
1. through the Open Narrative I know exactly what happened, therefore can verify these cases (all are by firearm or stabbing).
2. I noticed that the WHOVA 2016 question Id10100 (adult_5_4) "...injury intentionally inflicted by someone else?" was usually not answered or even denied in our survey. When I set the answer to this question to 1 (=Yes), SmartVA correctly returns "Homicide" as the CoD in all 37 cases in our survey.

So, while one could argue that adult_5_2 should be answered with Yes in those cases, I would say Id10091 "... injured by a firearm" (followed by death) should be sufficient to select "Homicide".

**Comment by aflaxman** [comment]
Interesting!  There are "business rules" for some injuries, including [homicide](https://github.com/ihmeuw/SmartVA-Analyze/blob/31403c34cb3b0660fb48bb08ebc8287d2169746e/smartva/rules/homicide_adult.py), but when we implemented them, we thought in the case you face it would be a challenge to distinguish homicide (intentionally inflicted by someone else) from suicide.  Although it would be straightforward to modify the business rules to remove the requirement that `injury_by_other == True` in the business rule, I like your approach of setting the value to Yes as a preprocessing step better, because I see some risk that in a different setting it might be better to do a different preprocessing.

This is also a great reminder to me that the Open Narrative contains valuable information that is not being used to its full extent by SmartVA!

**Comment by aflaxman** [comment]
This is a finding that will be very interesting to some of the other scientists who are deep in the weeds trying to wring the most information possible out of VA interviews.  It would be great if you were able to share the code you used here, but I think you might also consider writing up your findings on this as a blog or even as a peer-reviewed paper.  I'm going to close this issue for now, but please re-open it if you are able to share code or want to discuss the details further.
